version: "3.8"                                          # 파일 규격 버전
services:                                               # 이 항목 밑에 실행하려는 컨테이너들을 정의
  database:
    image: mariadb
    container_name: mariadb-container
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./database
    environment:
      - MARIADB_DATABASE=loginDemo
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=1234
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/data:/var/lib/mysql
    ports:
      - "13305:3305"      # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)

  server:
    image: login-image
    container_name: login-container
    build: .
    depends_on:
      - database
    ports:
      - "8080:8080"
    restart: always
